metadata:
  name: vertx-istio-routing-service
  labels:
    app: vertx-istio-routing-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: vertx-istio-routing-service
