metadata:
  labels:
    version: a
    app: vertx-istio-routing-service
  name: vertx-istio-routing-service-a
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: vertx-istio-routing-service
        version: a
    spec:
      containers:
      - image: vertx-istio-routing-service-a:latest
        imagePullPolicy: Always
        name: vertx
        livenessProbe:
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreashold: 1
          timeoutSeconds: 1
          exec:
            command:
            - curl
            - http://localhost:8080/health
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreashold: 1
          timeoutSeconds: 1
          exec:
            command:
            - curl
            - http://localhost:8080/health
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - vertx
      from:
        kind: ImageStreamTag
        name: vertx-istio-routing-service-a:latest
    type: ImageChange
