apiVersion: v1
kind: Template
metadata:
  name: vertx-istio-routing-service-a
  annotations:
    description: The Istio Routing Mission shows routing with Istio
    tags: instant-app
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: vertx-istio-routing-service-a
    labels:
      booster: vertx-istio-routing-service
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime-vertx-istio-routing-service-a
    labels:
      booster: vertx-istio-routing-service-a
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: vertx-istio-routing-service-a
    labels:
      booster: vertx-istio-routing-service-a
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: vertx-istio-routing-service-a:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-vertx-istio-routing-service-a:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/vertx-istio-routing-parent/vertx-istio-routing-service-a
      prometheus.io/port: "9779"
      fabric8.io/scm-url: https://github.com/openshiftio/vertx-istio-routing-parent/vertx-istio-routing-service-a
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/vertx-istio-routing-parent/vertx-istio-routing-service-a
      fabric8.io/scm-tag: booster-parent-23
    labels:
      app: vertx-istio-routing-service
      expose: "true"
    name: vertx-istio-routing-service
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: vertx-istio-routing-service
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/vertx-istio-routing-parent/vertx-istio-routing-service-a
      fabric8.io/scm-url: https://github.com/openshiftio/vertx-istio-routing-parent/vertx-istio-routing-service-a
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/vertx-istio-routing-parent/vertx-istio-routing-service-a
      fabric8.io/scm-tag: booster-parent-23
    labels:
      version: a
      app: vertx-istio-routing-service
    name: vertx-istio-routing-service-a
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/vertx-istio-routing-parent/vertx-istio-routing-service-a
          sidecar.istio.io/inject: "true"
          fabric8.io/scm-url: https://github.com/openshiftio/vertx-istio-routing-parent/vertx-istio-routing-service-a
          fabric8.io/iconUrl: img/icons/vertx.svg
          fabric8.io/git-branch: master
          fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/vertx-istio-routing-parent/vertx-istio-routing-service-a
          fabric8.io/scm-tag: booster-parent-23
        labels:
          app: vertx-istio-routing-service
          version: a
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: vertx-istio-routing-service-a:latest
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - curl
              - http://localhost:8080/health
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 3
            timeoutSeconds: 1
          name: vertx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - curl
              - http://localhost:8080/health
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - vertx
        from:
          kind: ImageStreamTag
          name: vertx-istio-routing-service-a:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: vertx-istio-routing-service
      expose: "true"
    name: vertx-istio-routing-service
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: vertx-istio-routing-service
