apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: routing-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: client-virtual-service
spec:
  hosts:
  - '*'
  gateways:
  - routing-gateway
  http:
  - match:
    - uri:
        prefix: /example/
    - uri:
        prefix: /example
    rewrite:
      uri: /
    route:
    - destination:
        host: vertx-istio-routing-client
        port:
          number: 8080
